# tomcat-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: tomcat-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-container
        image: vasanthdocuser/vk-build:v1.0
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: tomcat-app
---
# nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat-np-service
  labels:
    app: tomcat-app-sr	
spec:
  selector:
    app: tomcat-app

  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
